export const GET_DAILY_DATA_ACTION = 'GET_DAILY_DATA_ACTION';
export const GET_DAILY_DATA_SUCCESS_ACTION = 'GET_DAILY_DATA_SUCCESS_ACTION';
export const GET_DAILY_DATA_FAILURE_ACTION = 'GET_DAILY_DATA_FAILURE_ACTION';
