export const GET_DAILY_DATA_ACTION = 'GET_DAILY_DATA_ACTION';
export const GET_DAILY_DATA_SUCCESS_ACTION = 'GET_DAILY_DATA_SUCCESS_ACTION';
export const GET_DAILY_DATA_FAILURE_ACTION = 'GET_DAILY_DATA_FAILURE_ACTION';

export const GET_RECOVERY_DATA_ACTION = 'GET_RECOVERY_DATA_ACTION';
export const GET_RECOVERY_DATA_SUCCESS_ACTION =
  'GET_RECOVERY_DATA_SUCCESS_ACTION';
export const GET_RECOVERY_DATA_FAILURE_ACTION =
  'GET_RECOVERY_DATA_FAILURE_ACTION';

export const GET_DEATHS_DATA_ACTION = 'GET_DEATHS_DATA_ACTION';
export const GET_DEATHS_DATA_SUCCESS_ACTION = 'GET_DEATHS_DATA_SUCCESS_ACTION';
export const GET_DEATHS_DATA_FAILURE_ACTION = 'GET_DEATHS_DATA_FAILURE_ACTION';
